#!/bin/sh

DIRS=$1

replace() {
 sed -i /include/s/'\"lvgl\/'/'\"'/g ${1}
 # sed -i /include/s/'\.\.\/\.\.\/'/''/g ${1}
 sed -i /include/s/'\.\.\/'/''/g ${1}
 sed -i /include/s/'\.\.\/'/''/g ${1}
 sed -i /include/s/'\.\.\/'/''/g ${1}

 # sed -i /include/s/">"/"\""/g ${1}
}

echo "$DIRS" | while read d ; do
  if test -n "$d" -a -d "$d"; then
    find "$d" -type f -name '*' | while read SRC; do
      replace "$SRC"
    done
  fi
done

# find lvgl ! -name '*.c' -delete
# find lvgl ! -name '*.h' -delete
# find lvgl ! -name '*.s' -delete


# SRC_DIR=/path_to_lgvl
# DST_DIR=/home/ram/_4/stm32_lvgl/STM32F407_LVGL_FSMC
#
# cd SRC_DIR
#
# SRC_DIR=./
# cp --parent $(find ${SRC_DIR}/lv_examples -name '*.c') ${DST_DIR}
# cp --parent $(find ${SRC_DIR}/lv_examples -name '*.h') ${DST_DIR}
# cp --parent $(find ${SRC_DIR}/lv_examples -name '*.s') ${DST_DIR}
#
# SRC_DIR=./
# cp --parent $(find ${SRC_DIR}/lvgl -name '*.c') ${DST_DIR}
# cp --parent $(find ${SRC_DIR}/lvgl -name '*.h') ${DST_DIR}
# cp --parent $(find ${SRC_DIR}/lvgl -name '*.s') ${DST_DIR}


